### ISSUE TITLE
Terms and definitions: rendering subsections in ISO 10303

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-iso#367]
When "Terms and definitions" section contains a subsection on second level (e.g. 1.1), it is rendered as a term, i.e. subsection title renders below its number, with smaller font size than for a regular subsection. However, ISO 10303 documents have subsections at second level, which aren't terms with their definitions. In case there is a subsection at third level (e.g. 1.1.1), this is recognized, and only that subsection on the third level is rendered as a term.

Following image illustrates this behavior:
![image](https://user-images.githubusercontent.com/55683568/81224699-681ae880-8fe8-11ea-971c-604a1a07277b.png)

The problem is that subsection style at the same level isn't consistent in this case, and we are also missing subsections which are recognized as terms in the ToC:
![image](https://user-images.githubusercontent.com/55683568/81225106-fe4f0e80-8fe8-11ea-9d60-7b5ed0136a61.png)

Original ToC contains following:
![image](https://user-images.githubusercontent.com/55683568/81225153-0c9d2a80-8fe9-11ea-8ec0-9bff0e8e6f1b.png)

Moreover, this is actually "Terms, definitions and abbreviations" section in the original document (which really includes Abbreviations as a subsection), but it is automatically renamed to "Terms and definitions" (which is probably in accordance to the new ISO document style).

[example.zip](https://github.com/metanorma/metanorma-iso/files/4589359/example.zip)

**Comment by opoudjis** [comment]
This may have been fixed in https://github.com/metanorma/metanorma-standoc/issues/270; @anermina please check with github metanorma-standoc

**Comment by anermina** [comment]
> This may have been fixed in [metanorma/metanorma-standoc#270](https://github.com/metanorma/metanorma-standoc/issues/270); @anermina please check with github metanorma-standoc

@opoudjis , unfortunately, described issue is still present with github metanorma-standoc.

**Comment by opoudjis** [comment]
@anermina, I admit to having trouble understanding the issue. 

If a terminal subclause of a terms clause is not a term, but a subclause with normal text, it needs to be indicated as such by putting `[.nonterm]` in the line before it.

**Comment by anermina** [comment]
Thank you @opoudjis , this solves the problem.
