### ISSUE TITLE
Encoding source code bolding and italics

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iso#649]
ISO styles support source code bolding and italics.

1. Metanorma supports them too -- but they are not documented on metanorma.org. We need text for that. The `pseudocode` block is also not documented on metanorma.org.

2. It seems that we only support code formatting inside inline source code?

This shows up in ISO 6709:
<img width="191" alt="Screenshot 2022-05-04 at 9 55 42 AM" src="https://user-images.githubusercontent.com/11865/166613613-ded1e2d2-456d-4bc3-84f3-52ab467c3dbe.png">

This works:
```adoc
`**CRScsd<**registryURL**>/**`
```

This doesn't:
```adoc
[source]
----
**CRScsd<**registryURL**>/**
----
```

**Comment by manuel489** [comment]
> It seems that we only support code formatting inside inline source code?

@ronaldtse I think in source block cases we need to use the *subs* attribute:

````
[source%unnumbered,subs="verbatim,quotes"]
----
**CRScsd<**registryURL**>/**
----
````

![Capture1](https://user-images.githubusercontent.com/33627611/166615988-75a0fb53-85df-4005-83fb-28342bfc4970.PNG)

More information in [Customize the Substitutions Applied to Blocks](https://docs.asciidoctor.org/asciidoc/latest/subs/apply-subs-to-blocks/).

**Comment by ronaldtse** [comment]
When using the Pseudocode block, it works but the formatting is not in the source code format (which is intended):
https://www.metanorma.org/author/topics/document-format/text/

```adoc
[pseudocode%unnumbered]
====
**CRScsd<**registryURL**>/**
====
```

<img width="241" alt="Screenshot 2022-05-04 at 11 07 37 AM" src="https://user-images.githubusercontent.com/11865/166618286-baf0bfa4-0357-4110-8001-7b4904f700ae.png">

I also discovered that if I use this syntax:
```adoc
[example]
====

[source]
----
my code
----
====
```

The Word output will not use monospace for the `my code`.

**Comment by ronaldtse** [comment]
I think this is fixed. We will have to document this behavior on metanorma.org. @manuel489 can you please help do that? Thanks!

**Comment by manuel489** [comment]
@ronaldtse,

> Metanorma supports them too -- but they are not documented on metanorma.org. We need text for that. The pseudocode block is also not documented on metanorma.org.

There is a documentation about pseudocode block: [Metnorma -- Source code](https://www.metanorma.org/author/topics/document-format/text/#source-code)


> I think this is fixed. We will have to document this behavior on metanorma.org.

What do we need to document, exactly?
* The fact that we need to use *subs* attribute to enable formatting in source blocks (but not so in pseudocode), or
* the fact that monospace text is not shown in source blocks when they are nested in example blocks?

**Comment by ronaldtse** [comment]
@manuel489 you're right! Instead of the `subs` attribute, we can use this:

```adoc
[source,ruby]
--
{{{*def*}}} method1(x)
  {{{<<method2-definition,method2>>}}}(x) + 3
end
--
```

Perhaps the best way is to create a blog post on how to encode source code with formatting.

> the fact that monospace text is not shown in source blocks when they are nested in example blocks?

This is a bug that has been fixed, no action is necessary there.

**Comment by manuel489** [comment]
> This is a bug that has been fixed, no action is necessary there.

Well, I'm still getting the error in DOC output with the latest release of metanorma-iso (2.1.1).

**Comment by manuel489** [comment]
> Perhaps the best way is to create a blog post on how to encode source code with formatting.

Ticket created.

**Comment by opoudjis** [comment]
> The pseudocode block is also not documented on metanorma.org.

https://www.metanorma.org/author/topics/document-format/text/#pseudocode

**Comment by opoudjis** [comment]
> ISO styles support source code bolding and italics.
> Metanorma supports them too -- but they are not documented on metanorma.org.

Added.

**Comment by opoudjis** [comment]
@manuel489 I cannot confirm:

````
[example]
====

[source]
----
my code
----
====
````

is generating as

<img width="248" alt="Screen Shot 2022-05-19 at 22 04 04" src="https://user-images.githubusercontent.com/1911039/169289160-9433bbc6-61ae-456e-8605-bcb69ee4dbb1.png">

for ISO, with

````
= ISO 9:1995(E)
:docnumber: 9
:ref-docnumber: ISO 9:1995(E)
:edition: 2
:copyright-year: 1995
:published-date: 1995-02-15
:language: fr
:title-intro-en: Information and documentation
:title-main-en: Transliteration of Cyrillic characters into Latin characters -- Slavic and non-Slavic languages
:title-intro-fr: Information et documentation
:title-main-fr: Translittération des caractères cyrilliques en caractères latins -- Langues slaves et non slaves
:doctype: international-standard
:docstage: 50
:docsubstage: 60
:technical-committee-number: 46
:technical-committee: Information and documentation
:workgroup-type: WG
:workgroup-number: 3
:workgroup: Conversion of written languages
:secretariat: AFNOR
:ics: 01.140.10
:keywords: documentation, translittération, caractère alphabétique, caractère cyrillique, caractère latin
:imagesdir: images
:mn-document-class: iso
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:toc-figures: true
:toc-tables: true
:docsubtype: vocabulary
````

@manuel489, could you send me a document where source code is failing to render in monospace for you?

**Comment by manuel489** [comment]
If I use the same attributes as you do, the problem solves.
Here is a configuration where the rendering problem appears: [example_issue.zip](https://github.com/metanorma/metanorma-iso/files/8729679/example_issue.zip)

**Comment by manuel489** [comment]
If I change the docstage to `50:60`, the problem solves. So it's a stylesheet selection issue.

**Comment by opoudjis** [comment]
In the new stylesheet, we get rid of div class="Example". In the original css, we retain it, but div class="Example" has a font setting, and that is clearly overriding the font setting of the sourcecode snippet it contains. The solution is to remove font settings from all divs in Word CSS: they should be set only at a paragraph level (which is indeed the case).
