### ISSUE TITLE
(ISO 6709) Remove section numbers from Example references if these are located on the same section as the examples

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-iso#654]
In relation to https://github.com/metanorma/iso-6709/issues/18:

Original:
![issue10_original](https://user-images.githubusercontent.com/33627611/166728242-731f75c4-c98d-431f-938b-5ee889a0ccda.PNG)

Generated:
![issue10_generated](https://user-images.githubusercontent.com/33627611/166728271-2c262eb7-4ef5-42b4-8de9-30795fa512bd.PNG)

**Comment by manuel489** [comment]
I've realized that this issue is not happening in other situations.
It seems that it occurs when the reference is nested in an block.
Like a list item.

**Comment by ronaldtse** [comment]
Looks like this is fixed now? @manuel489 can you help confirm? Thanks.

<img width="862" alt="Screenshot 2022-05-25 at 12 07 25 PM" src="https://user-images.githubusercontent.com/11865/170177678-c9ff1988-ef8d-4242-a72e-eecf64693da2.png">

**Comment by manuel489** [comment]
Sorry, I was wrong. The problem is still present:

![capture1](https://user-images.githubusercontent.com/33627611/170627683-c6df719c-5734-4981-b892-a765d0acfaaa.PNG)

**Comment by manuel489** [comment]
These references are inside an example block:

````
[[ex_7-3_2]]
[example]
====
[source%unnumbered]
----
40°26'27.00"N 105°45'17.00"W 3597.078mHt <EPSG:5498>
----

As in <<ex_7-3_1>>, this human-readable example depicts the same lat/lon
coordinate tuple and height. Here, the CRS identifier text string
contains a moderate level of ambiguity because the CRS shown in the
example assumes that the user community understands the meaning of
EPSG 5498. With accompanying documentation, the CRS identifier is
referable in certain situations.
====
````
Maybe that is the reason they include a section indicator.
Even when the content is from that same section.

**Comment by opoudjis** [comment]
Yes, the container reference is being added when the references are within an example, and that's a bug.

**Comment by opoudjis** [comment]
Examples are a legitimate cross-reference container for other things -- e.g. Example 3, Note 2. But the criterion on cross-referencing containers needs to be different for notes and examples: an example contains notes but not other examples!
